name: Do-Experiment
on: 
 push:
   branches:
   - master
   - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: npm install, build, and test
        run: |
          npm install
    - name: npm build
        run: |
          npm run build --if-present
    - name: npm test
        run: |
          npm test
      env:
        CI: true
