name: Do-Experiment
on: 
 push:
   branches:
   - master
   - release/*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build --if-present
    - name: npm test
      run: |
        npm test
    - name: Building Release Note
      run: |
        npx semantic-release
      env:
        CI: true
